/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import model.Home;
import model.ProfileDirectory;
import model.ProfileSummary;
import model.Work;
import javax.swing.JPanel;
/**
 *
 * @author krish
 */
public class CreatePersonJPanel extends javax.swing.JPanel {
    
   private JPanel userProcessContainer;
   private ProfileDirectory ProfileDirectory;
   private Work work;
   private Home home;
    

    /**
     * Creates new form CreatePersonJPanel
     * @param userProcessContainer
     * @param ProfileDirectory
     */
    public CreatePersonJPanel(JPanel userProcessContainer, ProfileDirectory ProfileDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ProfileDirectory = ProfileDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateDetails = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblHome = new javax.swing.JLabel();
        lblWork = new javax.swing.JLabel();
        lblHomeStreetAddress = new javax.swing.JLabel();
        lblHUnitNumber = new javax.swing.JLabel();
        lblHCity = new javax.swing.JLabel();
        lblHState = new javax.swing.JLabel();
        lblHZipCode = new javax.swing.JLabel();
        lblHLandmark = new javax.swing.JLabel();
        lblHTelephone = new javax.swing.JLabel();
        lblHPhNumber = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblWorkStreetAddress = new javax.swing.JLabel();
        lblWUnitNumber = new javax.swing.JLabel();
        lblWCity = new javax.swing.JLabel();
        lblWState = new javax.swing.JLabel();
        lblWZipCode = new javax.swing.JLabel();
        lblWLandmark = new javax.swing.JLabel();
        lblWTelephone = new javax.swing.JLabel();
        lblWPhNumber = new javax.swing.JLabel();
        txtHomeStreetAddress = new javax.swing.JTextField();
        txtHUnitNumber = new javax.swing.JTextField();
        txtHCity = new javax.swing.JTextField();
        txtHState = new javax.swing.JTextField();
        txtHZipCode = new javax.swing.JTextField();
        txtHLandmark = new javax.swing.JTextField();
        txtHPhNumber = new javax.swing.JTextField();
        txtWorkStreetAddress = new javax.swing.JTextField();
        txtWUnitNumber = new javax.swing.JTextField();
        txtWCity = new javax.swing.JTextField();
        txtWState = new javax.swing.JTextField();
        txtWZipCode = new javax.swing.JTextField();
        txtWLandmark = new javax.swing.JTextField();
        txtWTelephone = new javax.swing.JTextField();
        txtWPhNumber = new javax.swing.JTextField();
        txtHTelephone = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblCreateDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateDetails.setText("Create Details ");

        lblFirstName.setText("Enter First Name - >");

        lblLastName.setText("Enter Last Name - >");

        lblAge.setText("Enter Age - >");

        lblHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHome.setText("Home Address");

        lblWork.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWork.setText("Work Address");

        lblHomeStreetAddress.setText("Street Address");

        lblHUnitNumber.setText("Unit Number");

        lblHCity.setText("City");

        lblHState.setText("State");

        lblHZipCode.setText("ZipCode");

        lblHLandmark.setText("Landmark");

        lblHTelephone.setText("Telephone");

        lblHPhNumber.setText("PhNumber");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblWorkStreetAddress.setText("Street Address");

        lblWUnitNumber.setText("Unit Number ");

        lblWCity.setText("City");

        lblWState.setText("State");

        lblWZipCode.setText("ZipCode");

        lblWLandmark.setText("Landmark");

        lblWTelephone.setText("Telephone");

        lblWPhNumber.setText("PhNumber");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(230, 230, 230)
                                .addComponent(lblCreateDetails))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblLastName))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(txtLastName))
                                .addGap(201, 201, 201)
                                .addComponent(lblAge)
                                .addGap(18, 18, 18)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHomeStreetAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHUnitNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHZipCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHLandmark, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHTelephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHPhNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHLandmark)
                                            .addComponent(lblHZipCode)
                                            .addComponent(lblHTelephone)
                                            .addComponent(lblHPhNumber)
                                            .addComponent(lblHomeStreetAddress)
                                            .addComponent(lblHUnitNumber)
                                            .addComponent(lblHCity)
                                            .addComponent(lblHState))
                                        .addGap(270, 270, 270))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblHome)
                                        .addGap(132, 132, 132)))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWorkStreetAddress)
                                    .addComponent(lblWUnitNumber)
                                    .addComponent(lblWCity)
                                    .addComponent(lblWState)
                                    .addComponent(lblWZipCode)
                                    .addComponent(lblWLandmark)
                                    .addComponent(lblWTelephone)
                                    .addComponent(lblWPhNumber))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWLandmark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWPhNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWorkStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWork))))))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtWCity, txtWLandmark, txtWPhNumber, txtWState, txtWTelephone, txtWUnitNumber, txtWZipCode, txtWorkStreetAddress});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtHCity, txtHLandmark, txtHPhNumber, txtHState, txtHTelephone, txtHUnitNumber, txtHZipCode, txtHomeStreetAddress});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateDetails)
                    .addComponent(btnBack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHome)
                            .addComponent(lblWork, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHomeStreetAddress)
                                    .addComponent(txtHomeStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHUnitNumber)
                                    .addComponent(txtHUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHCity)
                                    .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHState)
                                    .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHZipCode)
                                    .addComponent(txtHZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHLandmark)
                                    .addComponent(txtHLandmark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHTelephone)
                                    .addComponent(txtHTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHPhNumber)
                                    .addComponent(txtHPhNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWorkStreetAddress)
                                    .addComponent(txtWorkStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWUnitNumber)
                                    .addComponent(txtWUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWCity)
                                    .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWState)
                                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWZipCode)
                                    .addComponent(txtWZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWLandmark)
                                    .addComponent(txtWLandmark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWTelephone)
                                    .addComponent(txtWTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWPhNumber)
                                    .addComponent(txtWPhNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreate)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
          String FirstName = txtFirstName.getText();
          String LastName = txtLastName.getText();
          String Age = txtAge.getText();
          
          String HomeStreetAddress = txtHomeStreetAddress.getText();
          String HUnitNumber = txtHUnitNumber.getText();
          String HCity = txtHCity.getText();
          String HState = txtHState.getText();
          String HLandmark = txtHLandmark.getText();
          String HZipCode = txtHZipCode.getText();
          String HTelephone = txtHTelephone.getText();
          String HPhNumber = txtHPhNumber.getText();
        
        String WorkStreetAddress = txtWorkStreetAddress.getText();
        String WUnitNumber = txtWUnitNumber.getText();
        String WCity = txtWCity.getText();
        String WState = txtWState.getText();
        String WLandmark = txtWLandmark.getText();
        String WZipCode = txtWZipCode.getText();
        String WTelephone = txtWTelephone.getText();
        String WPhNumber = txtWPhNumber.getText();
        
        // Check if any of the fields are empty
if (FirstName.isEmpty() || LastName.isEmpty() || Age.isEmpty() ||
    HomeStreetAddress.isEmpty() || HUnitNumber.isEmpty() || HCity.isEmpty() ||
    HState.isEmpty() || HLandmark.isEmpty() || HZipCode.isEmpty() || 
    HTelephone.isEmpty() || HPhNumber.isEmpty() ||
    WorkStreetAddress.isEmpty() || WUnitNumber.isEmpty() || WCity.isEmpty() ||
    WState.isEmpty() || WLandmark.isEmpty() || WZipCode.isEmpty() || 
    WTelephone.isEmpty() || WPhNumber.isEmpty()) {
    
    // Show an error message if any field is empty
    JOptionPane.showMessageDialog(null, "All fields are mandatory. Please fill in all the details.");
} else {
        
        Work work = new Work(WorkStreetAddress, WUnitNumber.charAt(0), WCity, WState, WZipCode, WLandmark, Long.valueOf(WTelephone), WPhNumber);
        Home home = new Home(HomeStreetAddress, HUnitNumber.charAt(0), HCity, HState, HZipCode, HLandmark, Long.valueOf(HTelephone), HPhNumber);
       
        ProfileSummary profile = ProfileDirectory.addProfile(FirstName, LastName, work, home, Integer.valueOf(Age));
        
        JOptionPane.showMessageDialog(null, "Person Profile created successfully!");
        
        txtFirstName.setText(""); 
        txtLastName.setText("");
        txtAge.setText("");

        txtHomeStreetAddress.setText("");
        txtHUnitNumber.setText("");
        txtHCity.setText("");
        txtHState.setText("");
        txtHLandmark.setText("");
        txtHZipCode.setText("");
        txtHTelephone.setText("");
        txtHPhNumber.setText("");
        
        txtWorkStreetAddress.setText("");
        txtWUnitNumber.setText("");
        txtWCity.setText("");
        txtWState.setText("");
        txtWLandmark.setText("");
        txtWZipCode.setText("");
        txtWTelephone.setText("");
        txtWPhNumber.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed

    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCreateDetails;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHLandmark;
    private javax.swing.JLabel lblHPhNumber;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHTelephone;
    private javax.swing.JLabel lblHUnitNumber;
    private javax.swing.JLabel lblHZipCode;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHomeStreetAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWLandmark;
    private javax.swing.JLabel lblWPhNumber;
    private javax.swing.JLabel lblWState;
    private javax.swing.JLabel lblWTelephone;
    private javax.swing.JLabel lblWUnitNumber;
    private javax.swing.JLabel lblWZipCode;
    private javax.swing.JLabel lblWork;
    private javax.swing.JLabel lblWorkStreetAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHLandmark;
    private javax.swing.JTextField txtHPhNumber;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHTelephone;
    private javax.swing.JTextField txtHUnitNumber;
    private javax.swing.JTextField txtHZipCode;
    private javax.swing.JTextField txtHomeStreetAddress;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWLandmark;
    private javax.swing.JTextField txtWPhNumber;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWTelephone;
    private javax.swing.JTextField txtWUnitNumber;
    private javax.swing.JTextField txtWZipCode;
    private javax.swing.JTextField txtWorkStreetAddress;
    // End of variables declaration//GEN-END:variables
}
