/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import model.Home;
import model.ProfileDirectory;
import model.ProfileSummary;
import model.Work;


/**
 *
 * @author krish
 */
public class MainJFrame extends javax.swing.JFrame {

    private ProfileDirectory ProfileDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.ProfileDirectory = new ProfileDirectory();
        createInitialProfileSummary();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ProfileSummary = new javax.swing.JPanel();
        lblProfileSummary = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        lblView = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblUserControlDashboard = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        ProfileSummary.setBackground(new java.awt.Color(204, 204, 255));
        ProfileSummary.setForeground(new java.awt.Color(204, 255, 204));

        lblProfileSummary.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblProfileSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfileSummary.setText("Profile Summary");

        lblAdd.setText("Add your details here -> ");

        lblSearch.setText("Search your details here - >");

        lblView.setText("View your details here - >");

        lblUserControlDashboard.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblUserControlDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserControlDashboard.setText("User Control Dashboard");

        btnCreate.setText("Create Person");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View Person");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfileSummaryLayout = new javax.swing.GroupLayout(ProfileSummary);
        ProfileSummary.setLayout(ProfileSummaryLayout);
        ProfileSummaryLayout.setHorizontalGroup(
            ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileSummaryLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblView)
                    .addComponent(lblAdd))
                .addGap(18, 18, 18)
                .addGroup(ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate)
                    .addComponent(btnView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileSummaryLayout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileSummaryLayout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(68, 68, 68))))
            .addGroup(ProfileSummaryLayout.createSequentialGroup()
                .addGroup(ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileSummaryLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(lblProfileSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileSummaryLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(lblUserControlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        ProfileSummaryLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate, btnView});

        ProfileSummaryLayout.setVerticalGroup(
            ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileSummaryLayout.createSequentialGroup()
                .addGroup(ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileSummaryLayout.createSequentialGroup()
                        .addComponent(lblProfileSummary)
                        .addGap(34, 34, 34)
                        .addComponent(lblUserControlDashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdd)
                            .addComponent(btnCreate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblView)
                            .addComponent(btnView)))
                    .addGroup(ProfileSummaryLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfileSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        jSplitPane1.setTopComponent(ProfileSummary);

        userProcessContainer.setBackground(new java.awt.Color(204, 204, 204));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel panel = new CreatePersonJPanel(userProcessContainer, ProfileDirectory);
       userProcessContainer.add ("CreatePersonJPanel", panel);
       CardLayout layout = (CardLayout)userProcessContainer .getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewListJPanel panel = new ViewListJPanel(userProcessContainer, ProfileDirectory);
       userProcessContainer.add ("ViewListJPanel", panel);
       CardLayout layout = (CardLayout)userProcessContainer .getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchText = txtSearch.getText().trim();
        String firstName = "";
        String lastName = "";
        String workStreetAddress = "";
        String homeStreetAddress = "";

        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a search term (name or address)!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Check if the input contains a space (potential full name)
        if (searchText.contains(" ")) {
            String[] nameParts = searchText.split("\\s+", 2);
            firstName = nameParts[0];
            lastName = nameParts[1];
            workStreetAddress = firstName;
            homeStreetAddress = lastName;
        } else {
            // If no space, treat as either first name, last name, or address
            firstName = searchText;
            lastName = searchText;
            workStreetAddress = searchText;
            homeStreetAddress = searchText;
        }

        ProfileSummary result = ProfileDirectory.searchProfileSummary(firstName, lastName, workStreetAddress, homeStreetAddress);

        if (result == null) {
            JOptionPane.showMessageDialog(null, "Person not found!", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            SearchJPanel panel = new SearchJPanel(userProcessContainer, result);
            userProcessContainer.add("ViewListJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProfileSummary;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblProfileSummary;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblUserControlDashboard;
    private javax.swing.JLabel lblView;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void createInitialProfileSummary() {
        
        String[] FirstNames = {"Emma", "Liam", "Olivia", "Noah", "Ava"};
        String[] LastNames = {"Smith", "Johnson", "Williams", "Brown", "Jones"};
        String[] Cities = {"Los Angeles", "New York", "Chicago", "Houston", "Phoenix"};
        String[] States = {"CA", "NY", "IL", "TX", "AZ"};
        String[] Landmarks = {"Hollywood Sign", "Statue of Liberty", "Willis Tower", "Space Center Houston", "Desert Botanical Garden"};
        String[] ZipCodes = {"90001", "10001", "60601", "77001", "85001"};
        String[] UnitNumbers = {"Unit 101", "Unit 202", "Unit 303", "Unit 404", "Unit 505"};
        String[] Ages = {"24", "29", "31", "27", "22"}; // Updated age values

// Loop through arrays only up to the length of the arrays
    for (int i = 0; i < FirstNames.length; i++) {
        String FirstName = FirstNames[i];
        String LastName = LastNames[i];
        String City = Cities[i];
        String State = States[i];
        String Landmark = Landmarks[i];
        String Zipcode = ZipCodes[i];
        String UnitNumber = UnitNumbers[i];
        String Age = Ages[i]; // Add the corresponding age

    // Create Work and Home objects with appropriate details
    Work work = new Work("123 Adem st", UnitNumber.charAt(0), City, "CA", Landmark, "0213",Long.valueOf("1234567890"), "012");
    Home home = new Home("41 Calumet st", UnitNumber.charAt(0), City, "NY", Landmark, " 2341", Long.valueOf("0987654321"), "210");
   
    // Add profile using correct parameter order (work first, then home, then age)
    ProfileSummary  profile = ProfileDirectory.addProfile(FirstName, LastName, work, home, Integer.valueOf(Age));
}
    }
}
