/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import model.Home;
import model.ProfileSummary;
import model.Work;

/**
 *
 * @author krish
 */
public class SearchJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ProfileSummary profileSummary;
    private Work work;
    private Home home;
    /**
     * Creates new form SearchJPanel
     * @param userProcessContainer
     * @param profileSummary
     */
    public SearchJPanel(JPanel userProcessContainer, ProfileSummary profileSummary ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.profileSummary = profileSummary;
        
        populateProfileDetails();
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHTelephone = new javax.swing.JLabel();
        txtHUnitNumber = new javax.swing.JTextField();
        lblHPhNumber = new javax.swing.JLabel();
        txtHCity = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtHState = new javax.swing.JTextField();
        txtHZipCode = new javax.swing.JTextField();
        lblCreateDetails = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtHLandmark = new javax.swing.JTextField();
        txtHPhNumber = new javax.swing.JTextField();
        txtWorkStreetAddress = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtWUnitNumber = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtWCity = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtWState = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblWorkStreetAddress = new javax.swing.JLabel();
        txtWZipCode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblWUnitNumber = new javax.swing.JLabel();
        txtWLandmark = new javax.swing.JTextField();
        lblHome = new javax.swing.JLabel();
        lblWCity = new javax.swing.JLabel();
        txtWTelephone = new javax.swing.JTextField();
        lblWork = new javax.swing.JLabel();
        lblWState = new javax.swing.JLabel();
        lblHomeStreetAddress = new javax.swing.JLabel();
        lblWZipCode = new javax.swing.JLabel();
        lblHUnitNumber = new javax.swing.JLabel();
        txtWPhNumber = new javax.swing.JTextField();
        txtHTelephone = new javax.swing.JTextField();
        lblWLandmark = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblWTelephone = new javax.swing.JLabel();
        lblHCity = new javax.swing.JLabel();
        lblWPhNumber = new javax.swing.JLabel();
        lblHState = new javax.swing.JLabel();
        txtHomeStreetAddress = new javax.swing.JTextField();
        lblHZipCode = new javax.swing.JLabel();
        lblHLandmark = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblHTelephone.setText("Telephone");

        lblHPhNumber.setText("PhNumber");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblCreateDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateDetails.setText("Create Details ");

        lblFirstName.setText("Entered First Name ->");

        lblLastName.setText("Entered Last Name - >");

        lblAge.setText("Entered Age - >");

        lblWorkStreetAddress.setText("Street Address");

        lblWUnitNumber.setText("Unit Number ");

        lblHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHome.setText("Home Address");

        lblWCity.setText("City");

        lblWork.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWork.setText("Work Address");

        lblWState.setText("State");

        lblHomeStreetAddress.setText("Street Address");

        lblWZipCode.setText("ZipCode");

        lblHUnitNumber.setText("Unit Number");

        lblWLandmark.setText("Landmark");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblWTelephone.setText("Telephone");

        lblHCity.setText("City");

        lblWPhNumber.setText("PhNumber");

        lblHState.setText("State");

        lblHZipCode.setText("ZipCode");

        lblHLandmark.setText("Landmark");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHomeStreetAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHUnitNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHZipCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHLandmark, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHTelephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHPhNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHLandmark)
                                        .addComponent(lblHZipCode)
                                        .addComponent(lblHTelephone)
                                        .addComponent(lblHPhNumber)
                                        .addComponent(lblHomeStreetAddress)
                                        .addComponent(lblHUnitNumber)
                                        .addComponent(lblHCity)
                                        .addComponent(lblHState))
                                    .addGap(270, 270, 270))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblHome)
                                    .addGap(118, 118, 118)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblWorkStreetAddress)
                                .addComponent(lblWUnitNumber)
                                .addComponent(lblWCity)
                                .addComponent(lblWState)
                                .addComponent(lblWZipCode)
                                .addComponent(lblWLandmark)
                                .addComponent(lblWTelephone)
                                .addComponent(lblWPhNumber))
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtWUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWLandmark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWPhNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWorkStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblWork))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(278, 278, 278)
                            .addComponent(btnSave)
                            .addGap(136, 136, 136)
                            .addComponent(btnUpdate))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFirstName)
                                .addComponent(lblLastName))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFirstName)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(201, 201, 201)
                            .addComponent(lblAge)
                            .addGap(18, 18, 18)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(btnBack)
                            .addGap(230, 230, 230)
                            .addComponent(lblCreateDetails)
                            .addContainerGap(371, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSeparator1)
                            .addGap(17, 17, 17)))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtHCity, txtHLandmark, txtHPhNumber, txtHState, txtHTelephone, txtHUnitNumber, txtHZipCode, txtHomeStreetAddress});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtWCity, txtWLandmark, txtWPhNumber, txtWState, txtWTelephone, txtWUnitNumber, txtWZipCode, txtWorkStreetAddress});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWork, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHome, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHomeStreetAddress)
                                    .addComponent(txtHomeStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHUnitNumber)
                                    .addComponent(txtHUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHCity)
                                    .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHState)
                                    .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHZipCode)
                                    .addComponent(txtHZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHLandmark)
                                    .addComponent(txtHLandmark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHTelephone)
                                    .addComponent(txtHTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHPhNumber)
                                    .addComponent(txtHPhNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWorkStreetAddress)
                                    .addComponent(txtWorkStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWUnitNumber)
                                    .addComponent(txtWUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWCity)
                                    .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWState)
                                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWZipCode)
                                    .addComponent(txtWZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWLandmark)
                                    .addComponent(txtWLandmark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWTelephone)
                                    .addComponent(txtWTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWPhNumber)
                                    .addComponent(txtWPhNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCreateDetails)
                        .addComponent(btnBack))
                    .addGap(74, 74, 74)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(463, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionDisabled(){
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtAge.setEnabled(false);
        
        txtWorkStreetAddress.setEnabled(false);
        txtWUnitNumber.setEnabled(false);
        txtWCity.setEnabled(false);
        txtWState.setEnabled(false);
        txtWLandmark.setEnabled(false);
        txtWZipCode.setEnabled(false);
        txtWTelephone.setEnabled(false);
        txtWPhNumber.setEnabled(false);
        
        txtHomeStreetAddress.setEnabled(false);
        txtHUnitNumber.setEnabled(false);
        txtHCity.setEnabled(false);
        txtHState.setEnabled(false);
        txtHLandmark.setEnabled(false);
        txtHZipCode.setEnabled(false);
        txtHTelephone.setEnabled(false);
        txtHPhNumber.setEnabled(false);
    }
            
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Work work = new Work (txtWorkStreetAddress.getText(), txtWUnitNumber.getText().charAt(0),txtWCity.getText(),txtWState.getText(),txtWLandmark.getText(), txtWZipCode.getText(),Long.valueOf(txtWTelephone.getText()),txtWPhNumber.getText());
        Home home = new Home (txtHomeStreetAddress.getText(), txtHUnitNumber.getText().charAt(0),txtHCity.getText(),txtHState.getText(),txtHLandmark.getText(), txtHZipCode.getText(),Long.valueOf(txtHTelephone.getText()),txtHPhNumber.getText());
        
        profileSummary.setFirstName(txtFirstName.getText());
        profileSummary.setLastName (txtLastName.getText());
        profileSummary.setAge(Integer.valueOf(txtAge.getText()));
        
        profileSummary.setHome(home);
        profileSummary.setWork(work);
        
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnSaveActionDisabled();
        JOptionPane.showMessageDialog(null, "Person Details Saved Successfully");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtAge.setEnabled(true);
        
        txtWorkStreetAddress.setEnabled(true);
        txtWUnitNumber.setEnabled(true);
        txtWCity.setEnabled(true);
        txtWState.setEnabled(true);
        txtWLandmark.setEnabled(true);
        txtWZipCode.setEnabled(true);
        txtWTelephone.setEnabled(true);
        txtWPhNumber.setEnabled(true);
        
        txtHomeStreetAddress.setEnabled(true);
        txtHUnitNumber.setEnabled(true);
        txtHCity.setEnabled(true);
        txtHState.setEnabled(true);
        txtHLandmark.setEnabled(true);
        txtHZipCode.setEnabled(true);
        txtHTelephone.setEnabled(true);
        txtHPhNumber.setEnabled(true);
        
        btnSave.setEnabled(true);  
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCreateDetails;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHLandmark;
    private javax.swing.JLabel lblHPhNumber;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHTelephone;
    private javax.swing.JLabel lblHUnitNumber;
    private javax.swing.JLabel lblHZipCode;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHomeStreetAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWLandmark;
    private javax.swing.JLabel lblWPhNumber;
    private javax.swing.JLabel lblWState;
    private javax.swing.JLabel lblWTelephone;
    private javax.swing.JLabel lblWUnitNumber;
    private javax.swing.JLabel lblWZipCode;
    private javax.swing.JLabel lblWork;
    private javax.swing.JLabel lblWorkStreetAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHLandmark;
    private javax.swing.JTextField txtHPhNumber;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHTelephone;
    private javax.swing.JTextField txtHUnitNumber;
    private javax.swing.JTextField txtHZipCode;
    private javax.swing.JTextField txtHomeStreetAddress;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWLandmark;
    private javax.swing.JTextField txtWPhNumber;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWTelephone;
    private javax.swing.JTextField txtWUnitNumber;
    private javax.swing.JTextField txtWZipCode;
    private javax.swing.JTextField txtWorkStreetAddress;
    // End of variables declaration//GEN-END:variables

    private void populateProfileDetails() {
    txtFirstName.setText(profileSummary.getFirstName());

    txtLastName.setText(profileSummary.getLastName());
 
    txtAge.setText(String.valueOf(profileSummary.getAge()));
   

    // Set work address details in the text fields
    Work work = profileSummary.getWork();
    txtWorkStreetAddress.setText(profileSummary.getWork().getWorkStreetAddress());
    
    txtWUnitNumber.setText(Character.toString(profileSummary.getWork().getWUnitNumber()));
 
    txtWCity.setText(profileSummary.getWork().getWCity());
   
    txtWState.setText(profileSummary.getWork().getWState());
   
    txtWLandmark.setText(profileSummary.getWork().getWLandmark());

    txtWZipCode.setText(profileSummary.getWork().getWZipCode());

    txtWTelephone.setText(String.valueOf(profileSummary.getWork().getWTelephone()));
   
    txtWPhNumber.setText(profileSummary.getWork().getWPhNumber());
   

    // Set home address details in the text fields
    Home home = profileSummary.getHome();
    txtHomeStreetAddress.setText(profileSummary.getHome().getHomeStreetAddress());
    txtHUnitNumber.setText(Character.toString(profileSummary.getHome().getHUnitNumber()));
  
    txtHCity.setText(profileSummary.getHome().getHCity());

    txtHState.setText(profileSummary.getHome().getHState());
    
    txtHLandmark.setText(profileSummary.getHome().getHLandmark());
   
    txtHZipCode.setText(profileSummary.getHome().getHZipCode());
   
    txtHTelephone.setText(String.valueOf(profileSummary.getHome().getHTelephone()));
 
    txtHPhNumber.setText(profileSummary.getHome().getHPhNumber());
    
    btnSaveActionDisabled();
    btnSave.setEnabled(true);  // Allow the user to save the changes
    btnUpdate.setEnabled(false);
    }
}
