/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Home;
import model.ProfileDirectory;
import model.Work;
import model.ProfileSummary;
import javax.swing.table.DefaultTableModel;
import model.ViewList;
/**
 *
 * @author krish
 */
public class ViewListJPanel extends javax.swing.JPanel {

   private JPanel userProcessContainer;
   private ProfileDirectory ProfileDirectory;
   private Work work;
   private Home home;
    /**
     * Creates new form ViewListJPanel
     * @param userProcessContainer
     * @param ProfileDirectory
     */
    public ViewListJPanel(JPanel userProcessContainer, ProfileDirectory profileDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ProfileDirectory = profileDirectory;
        populateTable();
        
    }

       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewList = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lblViewList.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblViewList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewList.setText("View List");

        tblViewList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Work Address City", "Work Address ZipCode", "Home Adress City", "Home Address ZipCode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewList);
        if (tblViewList.getColumnModel().getColumnCount() > 0) {
            tblViewList.getColumnModel().getColumn(0).setResizable(false);
            tblViewList.getColumnModel().getColumn(1).setResizable(false);
            tblViewList.getColumnModel().getColumn(2).setResizable(false);
            tblViewList.getColumnModel().getColumn(3).setResizable(false);
            tblViewList.getColumnModel().getColumn(4).setResizable(false);
            tblViewList.getColumnModel().getColumn(5).setResizable(false);
        }

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblViewList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(357, 357, 357))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewList)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       DefaultTableModel dtm = (DefaultTableModel) tblViewList.getModel();
        int selectedRow = tblViewList.getSelectedRow();
        
        if (selectedRow >= 0) {
          String firstName = (String)  tblViewList.getValueAt(selectedRow,0);
          String lastName = (String)  tblViewList.getValueAt(selectedRow,1);
          ProfileSummary result = ProfileDirectory.searchProfileSummary(firstName, lastName, firstName, lastName );

          int dialogButton = JOptionPane.YES_NO_OPTION;
          int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected profile?", "Warning", JOptionPane.WARNING_MESSAGE);
          if (dialogResult == JOptionPane.YES_OPTION){
              dtm.removeRow(selectedRow);
            
           ProfileDirectory.deleteProfileSummary(result);
             // populateTable();
          }
        } else{
            JOptionPane.showMessageDialog(null, "Please select a row from the list", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewList;
    private javax.swing.JTable tblViewList;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblViewList.getModel();
            dtm.setRowCount(0);
            for(ProfileSummary profile: ProfileDirectory.getPersonList())
            {
              Work Work = profile.getWork();
              Home Home = profile.getHome();
              Object[] row = new Object[6];
              row[0] = profile.getFirstName();
              row[1] = profile.getLastName();
              if (Work != null){
                   row[2] = Work.getWCity();
                   row[3] = Work.getWZipCode();
              } else {
                  row[2] = "";
                  row[3] = "";
              }
              if (Home != null){
                   row[4] = Home.getHCity();
                   row[5] = Home.getHZipCode();
              }else {
                  row[4] = "";
                  row[5] = "";
              }
               dtm.addRow(row);
            }

    }
}
